apiVersion: v1
kind: Service
metadata:
  name: {{ include "insur-iq.fullname" . }}-backend
  labels:
    {{- include "insur-iq.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.backend.containerPort }}
      targetPort: http
  selector:
    {{- include "insur-iq.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insur-iq.fullname" . }}-web
  labels:
    {{- include "insur-iq.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.web.containerPort }}
      targetPort: http
  selector:
    {{- include "insur-iq.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "insur-iq.fullname" . }}-auth
  labels:
    {{- include "insur-iq.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.auth.containerPort }}
      targetPort: http
  selector:
    {{- include "insur-iq.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth
